FROM agostof/uwsgi-nginx-flask:python3.8-alpine
ENV STATIC_PATH /app/app/static
COPY ./src/requirements.txt .
RUN pip install -r requirements.txt
COPY ./src .

RUN mkdir -p /home/comments
COPY ./scripts/git-deploy.sh /usr/bin/
